import 'package:baduk_park/model/post_model.dart';
import 'package:flutter/widgets.dart';

class PostViewModelData with ChangeNotifier {
  PostPageListModel postModelDataPage1() {
    PostPageListModel postPageListModel = PostPageListModel(
      postPageListModel5: PostPageModel(
        postModelList1: PostModel(
          inputTime: DateTime(2022, 1, 1),
          userName: '에렌예거',
          keyword: 'KB한국바둑리그',
          commentCount: 0,
          title: '동해물과 백두산이',
        ),
        postModelList9: PostModel(
          inputTime: DateTime(2022, 1, 2),
          userName: '톰홀랜드',
          keyword: '중국갑조리그',
          commentCount: 0,
          title: '갑조리그에서 벌어진 일',
        ),
        postModelList10: PostModel(
          inputTime: DateTime(2022, 1, 3),
          userName: '토니스타크',
          keyword: '유럽바둑리그',
          commentCount: 0,
          title: '유럽바둑리그 어려움?',
        ),
        postModelList4: PostModel(
          inputTime: DateTime(2022, 1, 4),
          userName: '홍길동',
          keyword: '신진서',
          commentCount: 0,
          title: '진서한테 세점이면...',
        ),
        postModelList2: PostModel(
          inputTime: DateTime(2022, 1, 5),
          userName: '베르톨트',
          keyword: '이창호',
          commentCount: 0,
          title: '창호형 살아있네 ㅋㅋ',
        ),
        postModelList3: PostModel(
          inputTime: DateTime(2022, 1, 6),
          userName: '라이너',
          keyword: '응씨배',
          commentCount: 0,
          title: '다음 응씨배 누구꺼?',
        ),
        postModelList5: PostModel(
          inputTime: DateTime(2022, 1, 7),
          userName: '레온하트',
          keyword: '여자바둑리그',
          commentCount: 0,
          title: '여바리 게시판 관련 공지입니다.',
        ),
        postModelList6: PostModel(
          inputTime: DateTime(2022, 1, 8),
          userName: '후지사와',
          keyword: '일본 기성전',
          commentCount: 0,
          title: '기성전 상금이 아직도',
        ),
        postModelList7: PostModel(
          inputTime: DateTime(2022, 1, 9),
          userName: '시진핑',
          keyword: 'US오픈',
          commentCount: 0,
          title: 'US오픈 가서 재미봄ㅋㅋㅋ',
        ),
        postModelList8: PostModel(
          inputTime: DateTime(2022, 1, 10),
          userName: '김정은',
          keyword: '북조선바둑',
          commentCount: 0,
          title: '북조선 혁명바둑 만세',
        ),
      ),
      postPageListModel2: PostPageModel(
        postModelList1: PostModel(
          inputTime: DateTime(2022, 1, 1),
          userName: '에렌예거',
          keyword: 'KB한국바둑리그',
          commentCount: 0,
          title: '동해물과 백두산이',
        ),
        postModelList9: PostModel(
          inputTime: DateTime(2022, 1, 2),
          userName: '톰홀랜드',
          keyword: '중국갑조리그',
          commentCount: 0,
          title: '갑조리그에서 벌어진 일',
        ),
        postModelList10: PostModel(
          inputTime: DateTime(2022, 1, 3),
          userName: '토니스타크',
          keyword: '유럽바둑리그',
          commentCount: 0,
          title: '유럽바둑리그 어려움?',
        ),
        postModelList4: PostModel(
          inputTime: DateTime(2022, 1, 4),
          userName: '홍길동',
          keyword: '신진서',
          commentCount: 0,
          title: '진서한테 세점이면...',
        ),
        postModelList2: PostModel(
          inputTime: DateTime(2022, 1, 5),
          userName: '베르톨트',
          keyword: '이창호',
          commentCount: 0,
          title: '창호형 살아있네 ㅋㅋ',
        ),
        postModelList3: PostModel(
          inputTime: DateTime(2022, 1, 6),
          userName: '라이너',
          keyword: '응씨배',
          commentCount: 0,
          title: '다음 응씨배 누구꺼?',
        ),
        postModelList5: PostModel(
          inputTime: DateTime(2022, 1, 7),
          userName: '레온하트',
          keyword: '여자바둑리그',
          commentCount: 0,
          title: '여바리 게시판 관련 공지입니다.',
        ),
        postModelList6: PostModel(
          inputTime: DateTime(2022, 1, 8),
          userName: '후지사와',
          keyword: '일본 기성전',
          commentCount: 0,
          title: '기성전 상금이 아직도',
        ),
        postModelList7: PostModel(
          inputTime: DateTime(2022, 1, 9),
          userName: '시진핑',
          keyword: 'US오픈',
          commentCount: 0,
          title: 'US오픈 가서 재미봄ㅋㅋㅋ',
        ),
        postModelList8: PostModel(
          inputTime: DateTime(2022, 1, 10),
          userName: '김정은',
          keyword: '북조선바둑',
          commentCount: 0,
          title: '북조선 혁명바둑 만세',
        ),
      ),
      postPageListModel3: PostPageModel(
        postModelList1: PostModel(
          inputTime: DateTime(2022, 1, 1),
          userName: '에렌예거',
          keyword: 'KB한국바둑리그',
          commentCount: 0,
          title: '동해물과 백두산이',
        ),
        postModelList9: PostModel(
          inputTime: DateTime(2022, 1, 2),
          userName: '톰홀랜드',
          keyword: '중국갑조리그',
          commentCount: 0,
          title: '갑조리그에서 벌어진 일',
        ),
        postModelList10: PostModel(
          inputTime: DateTime(2022, 1, 3),
          userName: '토니스타크',
          keyword: '유럽바둑리그',
          commentCount: 0,
          title: '유럽바둑리그 어려움?',
        ),
        postModelList4: PostModel(
          inputTime: DateTime(2022, 1, 4),
          userName: '홍길동',
          keyword: '신진서',
          commentCount: 0,
          title: '진서한테 세점이면...',
        ),
        postModelList2: PostModel(
          inputTime: DateTime(2022, 1, 5),
          userName: '베르톨트',
          keyword: '이창호',
          commentCount: 0,
          title: '창호형 살아있네 ㅋㅋ',
        ),
        postModelList3: PostModel(
          inputTime: DateTime(2022, 1, 6),
          userName: '라이너',
          keyword: '응씨배',
          commentCount: 0,
          title: '다음 응씨배 누구꺼?',
        ),
        postModelList5: PostModel(
          inputTime: DateTime(2022, 1, 7),
          userName: '레온하트',
          keyword: '여자바둑리그',
          commentCount: 0,
          title: '여바리 게시판 관련 공지입니다.',
        ),
        postModelList6: PostModel(
          inputTime: DateTime(2022, 1, 8),
          userName: '후지사와',
          keyword: '일본 기성전',
          commentCount: 0,
          title: '기성전 상금이 아직도',
        ),
        postModelList7: PostModel(
          inputTime: DateTime(2022, 1, 9),
          userName: '시진핑',
          keyword: 'US오픈',
          commentCount: 0,
          title: 'US오픈 가서 재미봄ㅋㅋㅋ',
        ),
        postModelList8: PostModel(
          inputTime: DateTime(2022, 1, 10),
          userName: '김정은',
          keyword: '북조선바둑',
          commentCount: 0,
          title: '북조선 혁명바둑 만세',
        ),
      ),
      postPageListModel1: PostPageModel(
        postModelList1: PostModel(
          inputTime: DateTime(2022, 1, 1),
          userName: '에렌예거',
          keyword: 'KB한국바둑리그',
          commentCount: 0,
          title: '동해물과 백두산이',
        ),
        postModelList9: PostModel(
          inputTime: DateTime(2022, 1, 2),
          userName: '톰홀랜드',
          keyword: '중국갑조리그',
          commentCount: 0,
          title: '갑조리그에서 벌어진 일',
        ),
        postModelList10: PostModel(
          inputTime: DateTime(2022, 1, 3),
          userName: '토니스타크',
          keyword: '유럽바둑리그',
          commentCount: 0,
          title: '유럽바둑리그 어려움?',
        ),
        postModelList4: PostModel(
          inputTime: DateTime(2022, 1, 4),
          userName: '홍길동',
          keyword: '신진서',
          commentCount: 0,
          title: '진서한테 세점이면...',
        ),
        postModelList2: PostModel(
          inputTime: DateTime(2022, 1, 5),
          userName: '베르톨트',
          keyword: '이창호',
          commentCount: 0,
          title: '창호형 살아있네 ㅋㅋ',
        ),
        postModelList3: PostModel(
          inputTime: DateTime(2022, 1, 6),
          userName: '라이너',
          keyword: '응씨배',
          commentCount: 0,
          title: '다음 응씨배 누구꺼?',
        ),
        postModelList5: PostModel(
          inputTime: DateTime(2022, 1, 7),
          userName: '레온하트',
          keyword: '여자바둑리그',
          commentCount: 0,
          title: '여바리 게시판 관련 공지입니다.',
        ),
        postModelList6: PostModel(
          inputTime: DateTime(2022, 1, 8),
          userName: '후지사와',
          keyword: '일본 기성전',
          commentCount: 0,
          title: '기성전 상금이 아직도',
        ),
        postModelList7: PostModel(
          inputTime: DateTime(2022, 1, 9),
          userName: '시진핑',
          keyword: 'US오픈',
          commentCount: 0,
          title: 'US오픈 가서 재미봄ㅋㅋㅋ',
        ),
        postModelList8: PostModel(
          inputTime: DateTime(2022, 1, 10),
          userName: '김정은',
          keyword: '북조선바둑',
          commentCount: 0,
          title: '북조선 혁명바둑 만세',
        ),
      ),
      postPageListModel4: PostPageModel(
        postModelList1: PostModel(
          inputTime: DateTime(2022, 1, 1),
          userName: '에렌예거',
          keyword: 'KB한국바둑리그',
          commentCount: 0,
          title: '동해물과 백두산이',
        ),
        postModelList9: PostModel(
          inputTime: DateTime(2022, 1, 2),
          userName: '톰홀랜드',
          keyword: '중국갑조리그',
          commentCount: 0,
          title: '갑조리그에서 벌어진 일',
        ),
        postModelList10: PostModel(
          inputTime: DateTime(2022, 1, 3),
          userName: '토니스타크',
          keyword: '유럽바둑리그',
          commentCount: 0,
          title: '유럽바둑리그 어려움?',
        ),
        postModelList4: PostModel(
          inputTime: DateTime(2022, 1, 4),
          userName: '홍길동',
          keyword: '신진서',
          commentCount: 0,
          title: '진서한테 세점이면...',
        ),
        postModelList2: PostModel(
          inputTime: DateTime(2022, 1, 5),
          userName: '베르톨트',
          keyword: '이창호',
          commentCount: 0,
          title: '창호형 살아있네 ㅋㅋ',
        ),
        postModelList3: PostModel(
          inputTime: DateTime(2022, 1, 6),
          userName: '라이너',
          keyword: '응씨배',
          commentCount: 0,
          title: '다음 응씨배 누구꺼?',
        ),
        postModelList5: PostModel(
          inputTime: DateTime(2022, 1, 7),
          userName: '레온하트',
          keyword: '여자바둑리그',
          commentCount: 0,
          title: '여바리 게시판 관련 공지입니다.',
        ),
        postModelList6: PostModel(
          inputTime: DateTime(2022, 1, 8),
          userName: '후지사와',
          keyword: '일본 기성전',
          commentCount: 0,
          title: '기성전 상금이 아직도',
        ),
        postModelList7: PostModel(
          inputTime: DateTime(2022, 1, 9),
          userName: '시진핑',
          keyword: 'US오픈',
          commentCount: 0,
          title: 'US오픈 가서 재미봄ㅋㅋㅋ',
        ),
        postModelList8: PostModel(
          inputTime: DateTime(2022, 1, 10),
          userName: '김정은',
          keyword: '북조선바둑',
          commentCount: 0,
          title: '북조선 혁명바둑 만세',
        ),
      ),
    );

    notifyListeners();
    return postPageListModel;
  }
}
